export const altTexts = [
  [
    "Digital art. The comic shows a girl, 'Peanut butter girl', who has shoulder-length brown hair. The hair is straight and loose with a part in the middle of the head. The girl has brown eyes. Her face is facing a tall brown ledge that extends to her neck. On the shelf is a jar completely filled with peanut butter. The lid of this jar is red and the jar says 'Peanut Butter'. There is a picture of a peanut in a shell between the words 'Peanut' and 'butter'. The girl is smiling, staring at the jar and thinking, 'Aww ... we meet again, m'lady'. ",
  ],
  [
    "Digital art. The picture shows two friends standing next to each other. The girl on the left is slightly turned to the girl on the right. The girl on the left has blonde hair, green eyes, and is wearing a black blouse with small white polka dots. The girl on the right has brown hair, brown eyes, and is wearing a black blouse with thin straps and a plunging neckline. The girls are ready to go out to the party. The friends are smiling as they are in the process of taking another selfie before going out. Both girls have the same thought about this selfie - 'This time will be perfect ...'. In the lower left corner of the comic there is the inscription 'Selfie # 10244'",
  ],
  [
    "Digital art. The picture shows a girl sitting in a room with purple walls on a purple floor cross-legged in a meditation position. The girl has brown hair and a bun pinned up high. Her eyes are closed. The girl looks very focused. She is wearing a black tank top, dark purple leggings and black socks. At the height of her head, green shapes of electromagnetic waves can be seen on both sides. Next to it is a small brown cabinet with four drawers. There is a navy blue WIFI router on the cabinet, which also sends electromagnetic waves in navy blue. In the upper left corner of the picture there is a speech bubble saying: 'I will transfer my thougths to him, so that I will not have to tell about them'. On the right side of the wall there is a piece of paper with a red inscription 'No Hard Feelings'.",
  ],
  [
    "Digital art. The image shows a blueprint of a solution called 'Kissmaker 2000' that Peanut butter girl wants to build. According to the design, the device is a long stick that is attached to the waist with a belt and is so long and properly twisted that its end is at the level of the face. At the end of this stick is mounted mistletoe. In the left part of the project you can see the formula for the integral. In the lower right corner there is a red, filled heart, and next to the heart there is a red, unfilled mouth. The blueprint is on the brown table.",
    "Digital art. The picture shows the girl Peanut butter who is building the 'Kissmaker 2000'. The girl has long, brown loose hair. The girl is very focused on work. In the upper right corner of the picture there is a speech bubble saying: 'Almost there ...' In the lower right corner you can see two springs and three nuts. The background of the picture is pink.",
    "Digital art. The picture shows a Peanut butter girl who is standing in a room whose walls and floor are pale red. The girl is wearing a red knee-length dress with an open back. Her long brown hair is pulled up in a loose ponytail. The girl has the 'Kissmaker 2000' attached. At its end hangs a mistletoe with a red heart-shaped bow. The girl is standing in front of the brown door leading to a room called 'Sexi People Room'.",
  ],
  [
    "Digital art. The picture shows a girl wearing a yellow long-sleeved blouse and black leggings. Her hair is brown in a ponytail. The eyes are also brown. The girl is wearing orange headphones. The girl is dancing. Her left arm is stretched out in front of her and her right arm is placed on the waist. The background of the picture is blue. In the upper right corner there is a speech bubble with the word 'Dance' and its phonetic transcription. The flag of Great Britain is drawn in the lower right corner.",
  ],
];
