import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { ComicImage } from "../components/image";
import { Navigation } from "../components/navigation";
import { Text } from "../components/text";
import styles from "../styles/Home.module.css";
import { getEpisodes, groupFunction } from "../utils/episodes-handlers";
import { GetServerSideProps } from "next";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Text title={"Peanut butter girl comic"} />
      <ComicImage />
      <Navigation />
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  return {
    props: {},
  };
};

export default Home;
