import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { GetStaticProps } from "next";
import { Episode } from "../components/episode";
import { EpisodeType, getEpisodes } from "../utils/episodes-handlers";

const Home: NextPage<EpisodeType> = (props) => {
  const { name, images } = props;
  return (
    <div className={"max-w-screen"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Episode title={name} images={images} />
    </div>
  );
};

export const getStaticProps: GetStaticProps = (context) => {
  const lastEpisode = getEpisodes().at(-1) || {};
  return {
    props: lastEpisode,
  };
};

export default Home;
